# Generated by Django 3.2.16 on 2022-12-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancialibro',
            name='due_back',
            field=models.DateField(blank=True, help_text='Fecha de devolución', null=True),
        ),
    ]
